# Generated by Django 5.1.1 on 2024-09-29 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_frequency_remove_expense_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
    ]
